### ISSUE TITLE
3.4.1 - the versioning update

### ISSUE THREAD

**Issue by SparklingComet** [ShanerX/FakeTrollPlus#3]
3.4.1 - "The versioning update":
- make up-to-date result more "silent"
- use oop
- rename PluginBuild -> Updater
- nest enum called BuildType with the entries
- create a method to compare entries and detect whether the current version is NEWER
- nest an enum called RelationalStatus - BEHIND, CURRENT, AHEAD
- nest an enum called SemVer - MAJOR, MINOR, PATCH, BUILD_TYPE

**Comment by ShanerX** [comment]
Added in [54566c0](https://github.com/ShanerX/FakeTrollPlus/commit/54566c014343219f8ea915e9c9cd563aa6eb81f8).
